modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
    modId="energetictools"
    version="${file.jarVersion}"
    displayName="Better Dungeon Loot"
    credits="LegionModding"
    authors="Made with <3 by LegionModding"
    description='''This is just a mod which allows you to customize dungeon loot!'''
[[dependencies.energetictools]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.23,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energetictools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energetictools]]
    modId="yalm"
    mandatory=true
    versionRange="[forge-0.0.3,forge-0.1.0)"
    ordering="NONE"
    side="BOTH"